insert into grocery (name, price, section) values ('Aluminum Foil','8.84','miscellaneous');
insert into grocery (name, price, section) values ('Apples','10.81','produce');
insert into grocery (name, price, section) values ('Bacon','9.01','meat');
insert into grocery (name, price, section) values ('Bagles','10.67','bread');
insert into grocery (name, price, section) values ('Baguette/French Bread','5.01','bread');
insert into grocery (name, price, section) values ('Barbeque Sauce','16.96','packaged');
insert into grocery (name, price, section) values ('Butter','4.29','dairy');
insert into grocery (name, price, section) values ('Carrots','2.88','produce');
insert into grocery (name, price, section) values ('Cheese','1.75','dairy');
insert into grocery (name, price, section) values ('Coffee','6.17','packaged');
insert into grocery (name, price, section) values ('Cold Cuts','1.47','deli');
insert into grocery (name, price, section) values ('Cream Cheese','16.11','dairy');
insert into grocery (name, price, section) values ('Croissants','6.36','bread');
insert into grocery (name, price, section) values ('Eggs','2.66','dairy');
insert into grocery (name, price, section) values ('Fish','0.49','meat');
insert into grocery (name, price, section) values ('Flour','8.74','bulk');
insert into grocery (name, price, section) values ('Fruit','8.87','produce');
insert into grocery (name, price, section) values ('Grapes','8.78','produce');
insert into grocery (name, price, section) values ('Green Beans','7.86','produce');
insert into grocery (name, price, section) values ('Ground Beef','16.03','meat');
insert into grocery (name, price, section) values ('Ham','13.27','meat');
insert into grocery (name, price, section) values ('Honey','9.31','packaged');
insert into grocery (name, price, section) values ('Ice Cream','14.08','frozen');
insert into grocery (name, price, section) values ('Ketchup','2.94','packaged');
insert into grocery (name, price, section) values ('Lemons','17.24','produce');
insert into grocery (name, price, section) values ('Lettuc'e,'16.28','produce');
insert into grocery (name, price, section) values ('Milk','2.34','dairy';
insert into grocery (name, price, section) values ('Mushrooms','16.68','produce');
insert into grocery (name, price, section) values ('Oil'',5.25','packaged');
insert into grocery (name, price, section) values ('Onions','1.11','produce');
insert into grocery (name, price, section) values ('Orange Juice','2.52','frozen');
insert into grocery (name, price, section) values ('Oranges','3.40','produce');
insert into grocery (name, price, section) values ('Pasta','13.39','bulk');
insert into grocery (name, price, section) values ('Pizza','16.61','frozen');
insert into grocery (name, price, section) values ('Potatoes','13.29','produce');
insert into grocery (name, price, section) values ('Rice','5.23','bulk');
insert into grocery (name, price, section) values ('Salami','12.70','meat');
insert into grocery (name, price, section) values ('Soda','11.21','miscellaneous');
insert into grocery (name, price, section) values ('Sour Cream','1.73','dairy');
insert into grocery (name, price, section) values ('Tomatoes','1.56','produce');
insert into grocery (name, price, section) values ('Yogurt','18.67','dairy');
insert into grocery (name, price, section) values ();
insert into grocery (name, price, section) values ();
insert into grocery (name, price, section) values ();
insert into grocery (name, price, section) values ();
insert into grocery (name, price, section) values ();
insert into grocery (name, price, section) values ();
insert into grocery (name, price, section) values ();
insert into contacts (name, price, section) values ();
